name: Deploy VMs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
      location:
        description: 'Azure region'
        required: true
        default: 'eastus'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        run: |
          # Create resource group (suppress all output)
          az group create --name hybrid-ad-lab-${{ github.event.inputs.environment }}-rg --location ${{ github.event.inputs.location }} > /dev/null 2>&1
          
          # Deploy template (suppress all output)
          az deployment group create \
            --resource-group hybrid-ad-lab-${{ github.event.inputs.environment }}-rg \
            --template-file projects/hybrid-ad-lab/main.bicep \
            --parameters @projects/hybrid-ad-lab/main.parameters.json \
            --parameters projectName=hybrid-ad-lab \
            --parameters environment=${{ github.event.inputs.environment }} \
            --parameters location=${{ github.event.inputs.location }} > /dev/null 2>&1
          
          echo "✅ Deployment completed successfully!"

      - name: Show VMs
        run: |
          echo "=== VMs Deployed ==="
          az vm list --resource-group hybrid-ad-lab-${{ github.event.inputs.environment }}-rg --output table
