name: Deploy Azure IaC Project

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (folder under projects/)'
        required: true
        default: 'hybrid-ad-lab'
      environment:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
      location:
        description: 'Azure region'
        required: true
        default: 'eastus'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Install Bicep CLI
      - name: Install Bicep CLI
        run: az bicep install

      # 4. Check Bicep Version (debug step)
      - name: Check Bicep Version
        run: az bicep version

      # 5. Validate Bicep Template
      - name: Validate Bicep Template
        run: |
          echo "Validating Bicep for project ${{ github.event.inputs.project }}..."
          az bicep build --file projects/${{ github.event.inputs.project }}/main.bicep

      # 6. Create Resource Group
      - name: Create Resource Group
        run: |
          RG_NAME="${{ github.event.inputs.project }}-${{ github.event.inputs.environment }}-rg"
          echo "Creating resource group $RG_NAME..."
          az group create \
            --only-show-errors \
            --name $RG_NAME \
            --location ${{ github.event.inputs.location }} \
            --tags "Project=${{ github.event.inputs.project }}" "Environment=${{ github.event.inputs.environment }}" "DeployedBy=GitHubActions"

      # 7. Deploy Bicep Template
      - name: Deploy Bicep Template
        run: |
          RG_NAME="${{ github.event.inputs.project }}-${{ github.event.inputs.environment }}-rg"
          echo "Deploying ${{ github.event.inputs.project }} in $RG_NAME..."
          az deployment group create \
            --only-show-errors \
            --resource-group $RG_NAME \
            --template-file projects/${{ github.event.inputs.project }}/main.bicep \
            --parameters @projects/${{ github.event.inputs.project }}/main.parameters.json \
            --parameters \
                projectName=${{ github.event.inputs.project }} \
                environment=${{ github.event.inputs.environment }} \
                location=${{ github.event.inputs.location }}

      # 8. Get VM Public IPs
      - name: Get VM Public IPs
        run: |
          RG_NAME="${{ github.event.inputs.project }}-${{ github.event.inputs.environment }}-rg"
          echo "Fetching public IPs for VMs in $RG_NAME..."
          az vm list-ip-addresses --resource-group $RG_NAME --output table
