name: Deploy VMs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
      location:
        description: 'Azure region'
        required: true
        default: 'eastus'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        run: |
          RG_NAME="hybrid-ad-lab-${{ github.event.inputs.environment }}-rg"
          
          # Create resource group
          az group create --name $RG_NAME --location ${{ github.event.inputs.location }}
          
          # Deploy the template
          az deployment group create \
            --resource-group $RG_NAME \
            --template-file projects/hybrid-ad-lab/main.bicep \
            --parameters @projects/hybrid-ad-lab/main.parameters.json \
            --parameters projectName=hybrid-ad-lab \
            --parameters environment=${{ github.event.inputs.environment }} \
            --parameters location=${{ github.event.inputs.location }}

      - name: Show VMs
        run: |
          RG_NAME="hybrid-ad-lab-${{ github.event.inputs.environment }}-rg"
          echo "=== VMs Deployed ==="
          az vm list --resource-group $RG_NAME --output table
